#ifndef DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DISTRHO_PLUGIN_INFO_H_INCLUDED

#define DISTRHO_PLUGIN_BRAND   "Andrea"
#define DISTRHO_PLUGIN_NAME    "BlipMachine"
#define DISTRHO_PLUGIN_URI     "urn:andrea:blipmachine"
#define DISTRHO_PLUGIN_CLAP_ID "andrea.blipmachine"

#define DISTRHO_PLUGIN_BRAND_ID  Andr
#define DISTRHO_PLUGIN_UNIQUE_ID Blip

#define DISTRHO_PLUGIN_HAS_UI           0
#define DISTRHO_PLUGIN_IS_RT_SAFE       1
#define DISTRHO_PLUGIN_IS_SYNTH         1
#define DISTRHO_PLUGIN_NUM_INPUTS       0
#define DISTRHO_PLUGIN_NUM_OUTPUTS      2
#define DISTRHO_PLUGIN_WANT_MIDI_INPUT  1
#define DISTRHO_PLUGIN_WANT_MIDI_OUTPUT 0
#define DISTRHO_PLUGIN_WANT_TIMEPOS     0
#define DISTRHO_PLUGIN_LV2_CATEGORY     "lv2:InstrumentPlugin"

#endif
